server:
  port: 1347
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      test-while-idle: false
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://43.138.25.182:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
  swagger2:
    enabled: true
  application:
    name: redis_learn
  redis:
    password: 134679
    pool:
      connTimeout: 3000
      size: 10
      soTimeout: 3000
    single:
      address1: 43.138.25.182:6385
      address2: 43.138.25.182:6386
      address3: 43.138.25.182:6387
    mode: single
    timeout: 3000

  #在springboot2.6.X结合swagger2.9.X会提示documentationPluginsBootstrapper空指针异常，
  #原因是在springboot2.6.X中将SpringMVC默认路径匹配策略从AntPathMatcher更改为PathPatternParser，
  # 导致出错，解决办法是matching-strategy切换回之前ant_path_matcher
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
nacos:
  discovery:
    server-addr: 43.138.25.182:8848

